FROM node:16-alpine AS dev_deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:16-alpine AS build
WORKDIR /app
COPY . .
COPY --from=dev_deps /app/node_modules ./node_modules
RUN yarn build

EXPOSE 4000
